version: '3.7'

services:
  reading_api:
    build: .
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/code/src
    ports:
      - 8000:8000
    environment:
      - DB_HOST=reading_api_db
      - DB_NAME="${DB_NAME}"
      - DB_USER="${DB_USER}"
      - DB_PASSWORD="${DB_PASSWORD}
    depends_on:
      - reading_api_db
    restart: on-failure
    networks:
      - api-tier
      
  reading_api_db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - api-tier
    restart: always

volumes:
  db_data:

networks:
  api-tier: