---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapi-deployment
  labels:
    app: backendapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendapi
  template:
    metadata:
      labels:
        app: backendapi
    spec:
      containers:
        - name: backendapi
          image: backend-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-api-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              value: my_reading_db
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_HOST
              value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: backendapi-service
spec:
  type: NodePort
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: backendapi
  