apiVersion: v1
kind: Secret
metadata:
  name: backend-api-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQK


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres
data:
  POSTGRES_DB: my_reading_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password