name: Backedn API

on:
  push:
    paths:
    - 'src/*'

env:
  PYTHON_VERSION: 3.8
  POETRY_VERSION: 3.8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build API base image
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION}}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Build & Push Docker Image
      run: |
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u ehiaig --password-stdin
        docker image build -t ehiaig/backend-technical-api:v1.0 .
        docker push ehiaig/backend-technical-api:v1.0
