name: Backend API

on:
  push:
    branches:
      - main
    paths:
    - 'src/*'
      
jobs:
  build:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
    - name: Build API base image
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Build & Push Image
      run: |
        docker login --username ehiaig --password make2018$
        docker build -t ehiaig/backend-technical-test:v1.0 .
        docker push ehiaig/backend-technical-test:v1.0


# name: Backend API

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build and Publish Image
#     runs-on: ubuntu-latest

#     steps:
#     - name: Build API base image
#       uses: actions/checkout@v2

#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r ./requirements.txt

#     - name: Build & Push Docker Image
#       run: |
#         docker login --username ehiaig --password make2018$
#         docker build -t ehiaig/backend-technical-api:v1.0 .
#         docker push ehiaig/backend-technical-api:v1.0

#     - name: Start API service 
#       run: docker-compose up -d
#       - name: Run unit tests
#       if: ${{github.ref != 'refs/heads/main'}}
#       run: bash docker_scripts/run_unit_tests.sh

#     - name: Run tests with coverage
#       if: ${{github.ref != 'refs/heads/main'}}
#       uses: JamesIves/github-pages-deploy-action@4.1.2
#       with:
#         branch: gh-pages
#         folder: docs

#     - name: Deploy coverage report
#       if: ${{github.ref != 'refs/heads/main'}}
#       run: bash docker_scripts/run_test_coverage.sh

